import type { Menu, Reservation, Store } from "./domain";

export const seedReservations: Reservation[] = [
  {
    id: "RSV-1048",
    customer: "山田 美咲",
    email: "misaki@example.jp",
    date: "2026-07-12",
    startTime: "10:00",
    people: 2,
    menuItems: ["前菜盛り合わせ", "パスタランチ"],
    totalAmount: 7600,
    store: null,
    storeAssignments: [],
    status: "temporary_requested",
    confirmationContactedAt: null,
    received: "7月8日 09:42",
    phone: "090-1234-5678",
  },
  {
    id: "RSV-1047",
    customer: "佐藤 健太",
    email: "kenta@example.jp",
    date: "2026-07-10",
    startTime: "10:00",
    people: 1,
    menuItems: ["季節のコース"],
    totalAmount: 6600,
    store: "渋谷店",
    storeAssignments: [{ store: "渋谷店", people: 1 }],
    status: "waiting_for_visit",
    confirmationContactedAt: "2026-07-07T09:10:00.000Z",
    received: "7月7日 18:10",
    phone: "080-2345-6789",
  },
  {
    id: "RSV-1046",
    customer: "鈴木 由佳",
    email: "yuka@example.jp",
    date: "2026-07-15",
    startTime: "10:00",
    people: 3,
    menuItems: ["飲み放題プラン", "記念日プレート"],
    totalAmount: 16800,
    store: "新宿店",
    storeAssignments: [{ store: "新宿店", people: 3 }],
    status: "confirmed",
    confirmationContactedAt: null,
    received: "7月7日 14:25",
    phone: "070-3456-7890",
  },
  {
    id: "RSV-1045",
    customer: "高橋 直人",
    email: "naoto@example.jp",
    date: "2026-07-09",
    startTime: "10:00",
    people: 2,
    menuItems: ["パスタランチ"],
    totalAmount: 4000,
    store: "渋谷店",
    storeAssignments: [{ store: "渋谷店", people: 2 }],
    status: "cancellation_requested",
    confirmationContactedAt: null,
    received: "7月6日 11:03",
    phone: "090-4567-8901",
  },
  {
    id: "RSV-1044",
    customer: "伊藤 結衣",
    email: "yui@example.jp",
    date: "2026-07-08",
    startTime: "10:00",
    people: 1,
    menuItems: ["前菜盛り合わせ", "記念日プレート"],
    totalAmount: 4200,
    store: "横浜店",
    storeAssignments: [{ store: "横浜店", people: 1 }],
    status: "visited",
    confirmationContactedAt: "2026-07-07T07:30:00.000Z",
    received: "7月5日 16:30",
    phone: "080-5678-9012",
  },
];

export const seedMenus: Menu[] = [
  { name: "前菜盛り合わせ", description: "季節野菜と小皿料理の盛り合わせ", price: 1800, duration: "15分", displayOrder: 10 },
  { name: "パスタランチ", description: "本日のパスタ、サラダ、ドリンク付き", price: 2000, duration: "45分", displayOrder: 20 },
  { name: "季節のコース", description: "前菜、メイン、デザートまで楽しめるコース", price: 6600, duration: "90分", displayOrder: 30 },
  { name: "飲み放題プラン", description: "コースに追加できる90分飲み放題", price: 2800, duration: "90分", displayOrder: 40 },
  { name: "記念日プレート", description: "メッセージ付きデザートプレート", price: 2400, duration: "10分", displayOrder: 50 },
  { name: "来店後に注文", description: "来店後にメニューを注文します", price: 0, duration: "来店後", displayOrder: 999 },
];

export const seedStores: Store[] = [
  { name: "渋谷店", displayOrder: 10 },
  { name: "新宿店", displayOrder: 20 },
  { name: "横浜店", displayOrder: 30 },
];
